config/routes.rb
Rails.application.routes.draw do


  # ユーザー用
    devise_for :users,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }

  # 管理者用
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }

  namespace :public, path: '/' do
    root to: "homes#top"
    get "/about" => "homes#about"
    get "/user/confirmation" => "users#confirmation"
    resources "users", only: [:index, :show, :edit, :update, :confirmation]
    resources "cosplay_images" do
      resources "comments", only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get "search" => "searches#search"
    patch "/user/unsubscribe" => "users#unsubscribe"

  end

  #namespace :admin do
    #get       "/"      => "users#index"

  #end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer style="background-color: #38b48b;">
  <div class="container">
    <div class="row">
    	<div class="mx-auto my-3">
    	  CospRainbow
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header style="background-color: #38b48b;">
  <nav class="navbar navbar-expand-lg navbar navbar-light">
    <div class="container">
      <div class="row navbar-collapse" id="navbarNavDropdown">
        <div class="col-sm-2">
          <%= link_to public_root_path do %>
            <span class="text-light">CospRainbow</span>
          <% end %>
        </div>

          <% if user_signed_in? %>
            <div class="col-sm-5"></div>
            <div class="col-sm-5">
              <div>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <%= link_to public_user_path(current_user), class: "nav-link text-light" do %>
                      <i class="fas fa-user"></i>My page
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to public_cosplay_images_path, class: "nav-link text-light" do %>
                      <i class="fas fa-camera"></i>Cosplay
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to public_users_path, class: "nav-link text-light" do %>
                      <i class="fas fa-users"></i>Users
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                      <i class="fas fa-sign-out-alt"></i>Log out
                    <% end %>
                  </li>
                <% elsif admin_signed_in? %>
              <div class="col-sm-4"></div>
            <div class="col-sm-6">
              <div>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <!--<　%= link_to admin_items_path, class: "nav-link text-light" do %>-->
                      <i class="fas fa-camera"></i>Cosplay
                    <!--<　% end %>-->
                  </li>
                  <li class="nav-item">
                    <!--<　%= link_to admin_customers_path, class: "nav-link text-light" do %>-->
                      <i class="fas fa-users"></i>Users
                    <!--<　% end %>-->
                  </li>
                  <li class="nav-item">
                    <!--< %= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do %>-->
                      <i class="fas fa-sign-out-alt"></i>Log out
                    <!--< % end %>-->
                  </li>
              <% else %>
              <div class="col-sm-5"></div>
            <div class="col-sm-5">
              <div>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <%= link_to public_about_path, class: "nav-link text-light" do %>
                      <i class="fas fa-question"></i>About
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to public_cosplay_images_path, class: "nav-link text-light" do %>
                      <i class="fas fa-camera"></i>Cosplay
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                      <i class="fas fa-user-plus"></i>Sign up
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                      <i class="fas fa-sign-in-alt"></i>Log in
                    <% end %>
                  </li>
            <% end %>
                </ul>
                </div>

          </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CospRainbow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
  <main>
    <%= flash[:notice] %>
    <style>
      .table tr:hover td {
        background-color: #d6ffea;
      }
    </style>
    <div class = "container my-5">
      <%= yield %>
    </div>
  </main>
    <%= render "layouts/footer" %>
  </body>
</html>